baseurl = "https://ampergai.de"
languageCode = "de-BAR"
title = "Pfiff' ausm Ampergai"
theme = "kiss"
copyright = "2019 <a href=\"https://midzer.de\">midzer</a>"
disqusShortname = ""
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "midzer" # Author full name

[params.assets]
customCSS = [""]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
description = "Des is a Blog auf boarisch mid kurze Gschichtn ausm Lem. De Beiträg san ausm Ampergai um Minga rum. Fürn gloana Duascht wia a Pfiff' Bier. Zamleitn und Prost!"
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "midzer"
github = ""
email = ""
linkedin = ""
facebook = ""
instagram = ""
codepen = ""
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["twitter","github","email","email","linkedin","gitlab","rss"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
